#Docker compose version
version: '3.2'
services:
  alumnos-ds:
    container_name: seguimiento-academico-ds
    restart: always
    build: .
    command: python3 source/app.py runserver
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    links:
      - "memcached:memcached"

  memcached:
    container_name: memcached
    image: memcached:1.6.9
    restart: always
    ports:
      - 11211:11211
    command: -m 200m -I 50m
    
networks:
  default:
    external:
      name: seguimiento-academico